config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  resources :tweets do
    resource :likes, only: [:create, :destroy]
      resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet  
  belongs_to :user  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes
  has_one_attached :image
  def self.search(search)
    if search != ""
      Tweet.where('text LIKE(?)', "%#{search}%")
    else
      Tweet.all
    end
  end

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
  
  validates :name, :image,:text, presence: true 
  validates :text, length: { maximum: 168 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :password, format: { with: /\A[a-zA-Z0-9]+\z/ }
         validates :nickname, presence: true, length: { maximum: 12 }
         has_many :tweets
         has_one_attached :image
         has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from Exception, with: :error_handling
  rescue_from ActionController::RoutingError, with: :render_not_found
  def error_handling
    redirect_to root_path
  end
  def render_not_found
    redirect_to root_path
  end
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    redirect_to "/tweets/#{@comment.tweet.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_tweet

  def create
    like = current_user.likes.build(tweet_id: params[:tweet_id])
    like.save
    respond_to do |format|
      format.js
    end
  end

  def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
    respond_to do |format|
      format.js
    end
  end

  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :update, :destroy, :show]
before_action :move_to_index, except: [:index, :show, :search, :destroy, :update, :create, :new]
  before_action :authenticate_user!, only: [ :create, :edit, :update, :destroy]
  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to '/'
    else
      render :new
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_path
  end

  def edit
 
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
    redirect_to root_path
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user) 
  end

  def search
    @tweets = Tweet.search(params[:keyword])
  end

  private
  def tweet_params
    params.require(:tweet).permit(:name, :image, :text, :recipe, ).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def check_owner
    unless @tweet.user == current_user
      redirect_to root_path, alert: "You are not authorized for this action."
    end
  end

  def move_to_index
    unless user_signed_in? && current_user.id == @tweet.user_id
      redirect_to action: :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! 
  def show
    @nickname = current_user.nickname
    @tweets = current_user.tweets
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>cocktail tweet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">Coktail Tweet</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
                   <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %>
              </li>
            </ul>
          </span>
            <%= link_to "投稿する", new_tweet_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p>
         Coktail Tweet 2024.
      </p>
    </footer>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <%= form.text_field :name, placeholder: "タイトル" %>
  <%= form.file_field :image, direct_upload: true, data: { direct_upload_url: Rails.application.routes.url_helpers.rails_direct_uploads_path } %>
  <div id="previews">
    <% if @tweet.image.attached? %>
      <%= image_tag(@tweet.image, id: "preview_image") %>
    <% else %>
      <img id="preview_image">
    <% end %>
  </div>
  <%= form.text_area :text, placeholder: "レシピ、補足、168文字まで入力可能", rows: "10" %>
  <%= form.submit "SEND" %>
<% end %>

<% if @tweet.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>
    <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/tweets/create.js.erb
document.getElementById('like-btn<%= @tweet.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {tweet: @tweet}) %>"

app/views/tweets/destroy.js.erb
document.getElementById('like-btn<%= @tweet.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {tweet: @tweet}) %>"

app/views/tweets/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= render partial: "form", locals: { tweet: @tweet } %>
  </div>
</div>

app/views/tweets/index.html.erb
<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @tweets.each do |tweet| %>
     <div class="content_post" style="background-image: url(<%= url_for(tweet.image) if tweet.image.attached? %>);">
      <div class="more">
        <ul class="more_list">
          <li>
            <%= link_to '詳細', tweet_path(tweet.id) %>
          </li>
          <% if user_signed_in? && current_user.id == tweet.user_id %>
          <li>
            <%= link_to '編集', edit_tweet_path(tweet.id) %>
          </li>
          <li>
            <%= link_to '削除', tweet_path(tweet.id), data: { turbo_method: :delete } %>
          </li>
           <% end %>
        </ul>
      </div>
      <p><%= tweet.text %></p>
      <span class="name">
        <%= tweet.name %>
      
          <span>投稿者</span><%= tweet.user.nickname %>
      </span>
      
    </div>
  <% end %>
</div>

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= render partial: "form", locals: { tweet: @tweet } %>
  </div>
</div>

app/views/tweets/serch.html.erb
<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>
</div>

app/views/tweets/show.html.erb
<div class="contents row">
  <div class="content_post" style="background-image: url(<%= url_for(@tweet.image) if @tweet.image.attached? %>);">
   <% if user_signed_in? && current_user.id == @tweet.user_id %>
    <div class="more">
      <ul class="more_list">
        <li>
          <%= link_to '編集', edit_tweet_path(@tweet.id) %>
        </li>
        <li>
          <%= link_to '削除', tweet_path(@tweet.id), data: { turbo_method: :delete } %>
        </li>
      </ul>
    </div>
   <% end %>
    <p><%= @tweet.text %></p>
    <span class="name">
      <a href="/users/<%= @tweet.user.id %>">
        <span>投稿者</span><%= @tweet.user.nickname %>
      </a>
    </span>
  </div>
  <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@tweet, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
    
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>
  <% @tweets.each do |tweet| %>
     <div class="content_post" style="background-image: url(<%= url_for(tweet.image) if tweet.image.attached? %>);">
      <p><%= tweet.text %></p>
      <span class="name"><%= tweet.name %></span>
    </div>
  <% end %>
</div>